### ISSUE TITLE
mask expansion

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/steinbock#106]
nuclear segmentation followed by a simple user defined mask expansion would be a nice feature for future releases.

**Comment by a-rayford** [comment]
Agreed! I wanted to try this out as opposed to whole-cell segmentation (to see if it cuts down on neighboring cell spillover), will be nice to see this implemented. :)

**Comment by jwindhager** [comment]
Just FYI: considering to add this to the next release of steinbock, which, however, is only scheduled for end of June. Until then, you can perform mask expansion (morphological dilation) using CellProfiler (`steinbock apps cellprofiler`) shipped with the steinbock Docker container OOTB, see https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.1/modules/objectprocessing.html#expandorshrinkobjects.

**Comment by jwindhager** [comment]
Sorry both, this won't make it into the next release :-/
