### ISSUE TITLE
Unsupported Number of Dimension

### ISSUE THREAD

**Issue by lmhasse** [BodenmillerGroup/steinbock#108]
Hello Mr. Windhager,

I came across a problem running ```steinbock classify ilastik prepare --cropsize 50 --seed 123``` on my data. 
For context: The data I'm using are .tif files made in our institute. First of all I renamed them to .tiff for it to work at all (should be no problem, or?). If I understood correctly, the preprocessing step can be skipped if you're not starting from raw data.
Then I tried running the command I named before. I get an error message saying the number of dimensions (it says 4) is not supported. I started looking up the line throwing that error (l. 130 in io.py), and here's where the first question popped up in my head: why is there support for 2, 3, 5 and 6 dimensions, but not 4? I'm not that experienced with this kind of work so I would be highly interested in that.
But that 4 dimensions didn't make any sense, so I wrote a small Python program testing how many dimensions my .tiff-files have.
The code uses the same method ```img.ndim``` for the .tiff-files I read in with ```img = tifffile.imread("filepath")``` and prints out that there are only 3 dimensions. 
After running the code and throwing that error, the pixel_classifier.ilp is still created, but not the files in the folders ilastik_crops and ilastik_img. Running the code on the test data you provided works fine.
Could you help me figure out what's happening there? Could the reason be connected to a badly configured panel.csv file (I'm not sure if I configured it right, but I tried more than one possible variation)?

Kind regards,
Lucie Marie Hasse

**Comment by jwindhager** [comment]
Hi @lmhasse, thanks for reaching out!

> First of all I renamed them to .tiff for it to work at all (should be no problem, or?).

Indeed, as long as your TIFFs are in CYX dimension order, see the [specifications](https://bodenmillergroup.github.io/steinbock/latest/file-types/#images).

> If I understood correctly, the preprocessing step can be skipped if you're not starting from raw data.

Correct!

> why is there support for 2, 3, 5 and 6 dimensions, but not 4?

The rationale here was as follows: either the user provides single-channel (2 dimensions) or multi-channel (3 dimensions) images in the "correct" (C)YX format, or "full" TZCYX(S) (i.e., 5/6 channels) image stacks with T/Z/S=1. But you're right: considering that steinbock already assumes (C)YX or TZCYX(S) dimension order, we could also implement assumptions for 4 dimensions, e.g. (T/Z)CYX or CYXS. I will add this as a TODO for the next release. However, please note that steinbock "officially" (i.e., according to specifications, see the link above) only supports CYX images, so I'd recommend to always stick to this format.

> But that 4 dimensions didn't make any sense, so I wrote a small Python program testing how many dimensions my .tiff-files have. The code uses the same method `img.ndim` for the .tiff-files I read in with `img = tifffile.imread("filepath")` and prints out that there are only 3 dimensions. [...] Could you help me figure out what's happening there? 

Per default, `tifffile.imread` "squeezes away" dimensions of size 1, see [the tifffile source code](https://github.com/cgohlke/tifffile/blob/90805c33065da10d8e604850a840c3166099f91f/tifffile/tifffile.py#L3363). That why steinbock passes `squeeze=False` as a safety measure, see [here](https://github.com/BodenmillerGroup/steinbock/blob/main/steinbock/io.py#L138). I suspect that your TIFF files may be of shape `(1, C, Y, X)` or `(C, Y, X, 1)`. Could you maybe double-check with `squeeze=False` whether your images indeed only have three dimensions?

> Could the reason be connected to a badly configured panel.csv file (I'm not sure if I configured it right, but I tried more than one possible variation)?

If this was the case, steinbock should give a more helpful warning message, so I suspect that's not the case :-) Please have a look at the [panel file specifications](https://bodenmillergroup.github.io/steinbock/latest/file-types/#panel) if there is anything unclear.

Hope this helps!

**Comment by lmhasse** [comment]
Thank you so much for your response! It was indeed very helpful. 

I didn't check the dimension format. So that will propably solve the problem. Do you know a good website explaining that and how to change the format?
I was confused by the argument ```squeeze=false```, because my IDE (Pycharm) didn't suggest that as possible argument for the function ```.imread```.  But I will try that!

Have a nice day,
Lucie

**Comment by jwindhager** [comment]
Hi @lmhasse 

> Do you know a good website explaining that and how to change the format?

Unfortunately, I don't know of a good resource explaining the (rather complex) TIFF specifications in a straightforward way, and also the `tifffile` documentation doesn't seem to be up to nowadays standards... Regarding changing the format, it would probably be best to get the software producing the TIFF files to write them out as needed in the first place. If that doesn't work, you'll have to convert them manually, e.g. using ImageJ/Fiji or Python/tifffile as follows:
```python
import tifffile
from pathlib import Path

for img_file in Path("/path/to/img").glob("*.tiff"):
    zcyx_img = tifffile.imread(img_file, squeeze=False)
    assert zcyx_img.shape[0] == 1, f"{img_file.name} is a z-stack!"
    cyx_img = zcyx_img[0, :, :, :]
    tifffile.imwrite(img_file, data=cyx_img)
```

> I was confused by the argument `squeeze=false`, because my IDE (Pycharm) didn't suggest that as possible argument for the function `.imread`.

Unfortunately, the `tifffile` package is not written in a way that makes it easy for IDEs to properly discover function arguments.

I'll close this issue for now - please feel free to reopen it in case it isn't resolved! Cheers

**Comment by jwindhager** [comment]
Hi @lmhasse, really sorry that your experience with steinbock hasn't been smooth so far! Your code changes sound legit, assuming you indeed have CYXZ data. Would you be able to [share](mailto:jonas.windhager@uzh.ch) one of your TIFF files, so I can have a quick look at what is going on here? I'm not familiar with the Vectra format, but I suspect that there still is something off with the dimension order. Regarding the Bioformats tool: I don't know this one, so this is just a suspicion, but the tool *may* just show/change the OME-XML metadata rather than the TIFF header metadata.

**Comment by jwindhager** [comment]
Assuming this has been resolved offline, please reopen the issue if that's not the case.

For completeness, this was my reply to the offline request:
![image](https://user-images.githubusercontent.com/7105759/160496248-cfb8031f-dcf4-4e0c-9b16-5dacbaa3e5fc.png)
