### ISSUE TITLE
steinbock classify ilastik prepare

### ISSUE THREAD

**Issue by sailseem** [BodenmillerGroup/steinbock#110]
Dear developer,

This steinbock gonna make IMC life so easy, while when i am following the instructions, I got an error when I performed the ilastik prepare

 steinbock classify ilastik prepare --cropsize 50 --seed 123

ilastik_img/20210305_NE_mockData1_001.h5
ilastik_img/20210305_NE_mockData1_002.h5
ilastik_img/20210305_NE_mockData1_003.h5
ilastik_img/20210305_NE_mockData2_001.h5
ilastik_img/20210305_NE_mockData2_002.h5
ilastik_img/20210305_NE_mockData2_003.h5
ilastik_img/20210305_NE_mockData3_001.h5
ilastik_img/20210305_NE_mockData3_002.h5
ilastik_img/20210305_NE_mockData3_003.h5
ilastik_img/20210305_NE_mockData4_001.h5
ilastik_img/20210305_NE_mockData4_002.h5
ilastik_img/20210305_NE_mockData4_003.h5
ilastik_img/20210305_NE_mockData5_001.h5
ilastik_img/20210305_NE_mockData5_002.h5
ilastik_img/20210305_NE_mockData5_003.h5
ilastik_crops/20210305_NE_mockData1_001_x1_y47_w50_h50.h5
ilastik_crops/20210305_NE_mockData1_002_x46_y2_w50_h50.h5
ilastik_crops/20210305_NE_mockData1_003_x45_y7_w50_h50.h5
ilastik_crops/20210305_NE_mockData2_001_x39_y22_w50_h50.h5
ilastik_crops/20210305_NE_mockData2_002_x22_y12_w50_h50.h5
ilastik_crops/20210305_NE_mockData2_003_x19_y47_w50_h50.h5
ilastik_crops/20210305_NE_mockData3_001_x35_y46_w50_h50.h5
ilastik_crops/20210305_NE_mockData3_002_x30_y16_w50_h50.h5
ilastik_crops/20210305_NE_mockData3_003_x85_y34_w50_h50.h5
ilastik_crops/20210305_NE_mockData4_001_x17_y7_w50_h50.h5
ilastik_crops/20210305_NE_mockData4_002_x1_y20_w50_h50.h5
ilastik_crops/20210305_NE_mockData4_003_x30_y14_w50_h50.h5
ilastik_crops/20210305_NE_mockData5_001_x15_y39_w50_h50.h5
ilastik_crops/20210305_NE_mockData5_002_x107_y18_w50_h50.h5
ilastik_crops/20210305_NE_mockData5_003_x54_y83_w50_h50.h5
Traceback (most recent call last):
  File "/usr/local/bin/steinbock", line 8, in <module>
    sys.exit(steinbock_cmd_group())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/steinbock/classification/_cli/ilastik.py", line 168, in prepare_cmd
    ilastik.create_and_save_ilastik_project(ilastik_crop_files, ilastik_project_file)
  File "/usr/local/lib/python3.9/site-packages/steinbock/classification/ilastik/_ilastik.py", line 219, in create_and_save_ilastik_project
    shutil.copyfile(_project_file_template, ilastik_project_file)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/steinbock/classification/ilastik/data/pixel_classifier.ilp'

Can you help me with it? Thanks

**Comment by jwindhager** [comment]
Hi @sailseem, thanks for reaching out! Uhm, that doesn't look good... Are you running steinbock using docker as explained [here](https://bodenmillergroup.github.io/steinbock/latest/install-docker/), or did you install it directly from PyPI using `pip install`?

**Comment by sailseem** [comment]
hi, i installed it from pip install under python 3.8, and I am using M1 chip MacBook. Thanks

**Comment by jwindhager** [comment]
Alright, it seems that the default Ilastik project file does not get shipped with binary distributions of steinbock from PyPI. I will release a fix with the next version. Until then, please use the Docker version of steinbock or manually download the Ilastik project file from https://github.com/BodenmillerGroup/steinbock/tree/main/steinbock/classification/ilastik/data.

In general, especially when using the Ilastik/CellProfiler-based approach for segmentation, I recommend to use the Docker version of steinbock, as it ships with tested versions of Ilastik & CellProfiler. As stated [here](https://bodenmillergroup.github.io/steinbock/latest/install-python/), directly installing steinbock from PyPI is intended for advanced use in Python scripts only.

**Comment by sailseem** [comment]
Thanks, but while I may have another issue, is this due to the compatibility of M1 chip?
alias steinbock="docker run -v /path/to/data:/data -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/home/steinbock/.Xauthority:ro -u $(id -u):$(id -g) -e DISPLAY=$(hostname):0 ghcr.io/bodenmillergroup/steinbock:0.13.5"

steinbock --version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: Mounts denied: 
The path /path/to/data is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
ERRO[0000] error waiting for container: context canceled

**Comment by jwindhager** [comment]
While there may indeed be problems with docker/tensorflow/deepcell on M1 systems (see [here](https://github.com/BodenmillerGroup/steinbock/issues/98)), your error is because of `/path/to/data` not existing. As explained in the docs:

> adapt the bind mount path to your data/working directory

**Comment by sailseem** [comment]
while when i put the path in still not running good, you were saying there is no way I can run it on M1 chip?

docker run -v /Users/yangfan/Documents/steinbock/data -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/home/steinbock/.Xauthority:ro -u $(id -u):$(id -g) -e DISPLAY=$(hostname):0 ghcr.io/bodenmillergroup/steinbock:0.13.5

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Usage: steinbock [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  preprocess  Extract and preprocess images from raw data
  classify    Perform pixel classification to extract probabilities
  segment     Perform image segmentation to create object masks
  measure     Extract object data from segmented images
  export      Export data to third-party formats
  utils       Various utilities and tools
  apps        Third-party applications

**Comment by jwindhager** [comment]
> docker run -v /Users/yangfan/Documents/steinbock/data -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/home/steinbock/.Xauthority:ro -u $(id -u):$(id -g) -e DISPLAY=$(hostname):0 ghcr.io/bodenmillergroup/steinbock:0.13.5

You seem to have accidentally deleted the colon (`:`) between `/Users/yangfan/Documents/steinbock` and `/data`

> while when i put the path in still not running good

What's the steinbock command you're trying to run? What's the error message?

> you were saying there is no way I can run it on M1 chip?

Steinbock SHOULD run without issues on M1 systems, but you MAY run into problems with DeepCell-related functionality. The Ilastik/CellProfiler functionality should work, though.

**Comment by sailseem** [comment]
Thanks a lot for pointing out my stupid problems, I can successfully run the code.
But when I excuted steinbock apps ilastik, I got errors like this. Does this mean I need to run ilastik manually to export HDF5 files? Sorry for these silly questions, I am totally new to this.


(base) yangfan@s-MacBook-Pro data % steinbock apps ilastik

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Fontconfig warning: "/opt/ilastik/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/opt/ilastik/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/opt/ilastik/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load config file from /opt/ilastik/etc/fonts/fonts.conf
/opt/ilastik/ilastik-meta/lazyflow/lazyflow/classifiers/__init__.py:20: UserWarning: init: Could not import tiktorch classifier
  warnings.warn("init: Could not import tiktorch classifier")
Starting ilastik from "/opt/ilastik".
QXcbConnection: Could not connect to display s-MacBook-Pro.local:0
Fatal Python error: Aborted

Thread 0x0000004039cc2700 (most recent call first):
  File "/opt/ilastik/lib/python3.7/threading.py", line 300 in wait
  File "/opt/ilastik/lib/python3.7/threading.py", line 552 in wait
  File "/opt/ilastik/lib/python3.7/threading.py", line 1156 in run
  File "/opt/ilastik/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/opt/ilastik/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x000000402fbe9700 (most recent call first):
  File "/opt/ilastik/lib/python3.7/threading.py", line 296 in wait
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 154 in _get_next_job
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 99 in run
  File "/opt/ilastik/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/opt/ilastik/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x0000004006136700 (most recent call first):
  File "/opt/ilastik/lib/python3.7/threading.py", line 296 in wait
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 154 in _get_next_job
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 99 in run
  File "/opt/ilastik/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/opt/ilastik/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x0000004006937700 (most recent call first):
  File "/opt/ilastik/lib/python3.7/threading.py", line 296 in wait
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 154 in _get_next_job
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 99 in run
  File "/opt/ilastik/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/opt/ilastik/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x0000004009138700 (most recent call first):
  File "/opt/ilastik/lib/python3.7/threading.py", line 296 in wait
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 154 in _get_next_job
  File "/opt/ilastik/ilastik-meta/lazyflow/lazyflow/request/threadPool.py", line 99 in run
  File "/opt/ilastik/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/opt/ilastik/lib/python3.7/threading.py", line 885 in _bootstrap

Current thread 0x0000004002d6d340 (most recent call first):
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 61 in startShellGui
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik_main.py", line 176 in main
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik.py", line 128 in main
  File "/opt/ilastik/ilastik-meta/ilastik/ilastik.py", line 134 in <module>
qemu: uncaught target signal 6 (Aborted) - core dumped
/opt/ilastik/run_ilastik.sh: line 77:    54 Aborted                 "${PREFIX}/bin/python" "${PREFIX}/ilastik-meta/ilastik/ilastik.py" "$@"

**Comment by jwindhager** [comment]
No worries! Did you start xquartz before executing the command, as described in the [installation instructions for MacOS](https://bodenmillergroup.github.io/steinbock/latest/install-docker/#macos)?

**Comment by jwindhager** [comment]
The Ilastik project file should've been generated by the `steinbock classify Ilastik prepare` command as explained in the docs. Did that command run without errors?

**Comment by sailseem** [comment]
no errors this one steinbock classify ilastik prepare --cropsize 50 --seed 123
 , and i got the project file 
![image](https://user-images.githubusercontent.com/72428172/158256332-87be18a0-b9e9-45cc-8195-bd954d500a11.png)

**Comment by jwindhager** [comment]
Are you using the identical steinbock `alias` for both commands? It seems that there's something wrong with the bind mount again, otherwise you'd see the same data in the Ilastik file browser...

**Comment by sailseem** [comment]
well, i made a picture, wish you can understand, I just followed the instruction
![image](https://user-images.githubusercontent.com/72428172/158473486-46640c10-c5f9-43bb-b05c-28c44b2cf456.png)
![image](https://user-images.githubusercontent.com/72428172/158473508-7c65dc26-faa3-43d3-8324-f1ab8400f9a8.png)
![image](https://user-images.githubusercontent.com/72428172/158473527-037ff140-8f24-4be7-b2e5-38cfed631990.png)
![image](https://user-images.githubusercontent.com/72428172/158473538-d5cf1d16-cd98-4147-a29f-716441365ea0.png)

**Comment by sailseem** [comment]
i made a picture, hope you can understand
![image](https://user-images.githubusercontent.com/72428172/158473758-8742514d-4179-4869-8c99-1e7672cfcf2a.png)
![image](https://user-images.githubusercontent.com/72428172/158473781-b5eaa791-204d-4f8a-a1ab-65f49fd6fd5d.png)
![image](https://user-images.githubusercontent.com/72428172/158473800-e513706d-ade5-4e3a-9c2e-86e68bc8b85c.png)
![image](https://user-images.githubusercontent.com/72428172/158473833-f301da98-f1c1-40e5-a078-97fefb6bc7b5.png)

**Comment by jwindhager** [comment]
Thanks! From Ilastik, the `pixel_classifier.ilp` file should be accessible at `/data/pixel_classifier.ilp`, as mentioned in the [docs](https://bodenmillergroup.github.io/steinbock/latest/cli/classification/#training-the-classifier). If that's not the case, please fix your steinbock alias before running `steinbock apps ilastik`:
```
alias steinbock="docker run -v /Users/yangfan/Documents/steinbock/xx:data -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/home/steinbock/.Xauthority:ro -u $(id -u):$(id -g) -e DISPLAY ghcr.io/bodenmillergroup/steinbock:0.13.5"
steinbock apps ilastik
```

**Comment by sailseem** [comment]
alias steinbock="docker run -v /Users/yangfan/Documents/steinbock/xx:data -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/home/steinbock/.Xauthority:ro -u $(id -u):$(id -g) -e DISPLAY ghcr.io/bodenmillergroup/steinbock:0.13.5"
steinbock apps ilastik

this command returns 

![image](https://user-images.githubusercontent.com/72428172/158478306-050df14f-2380-43f5-ae33-061978900da4.png)

**Comment by jwindhager** [comment]
Sorry, missed a slash, edited my comment now.

**Comment by sailseem** [comment]
Thanks, while still errors， I feel so frustrated 😭  and wasted lots of your valuable time, maybe i am just not that smart enough to pull this off
![image](https://user-images.githubusercontent.com/72428172/158484119-91be3868-8b26-48c9-81e5-327c82a48471.png)
![image](https://user-images.githubusercontent.com/72428172/158484147-c306f7c1-7ce2-46df-b9b4-fd0384e1c684.png)

**Comment by jwindhager** [comment]
No worries, you can do this! Did you remember to start xquartz before running above commands?

**Comment by sailseem** [comment]
yes. opening all the time,

**Comment by sailseem** [comment]
The only difference between these two alias I noticed is "DISPLAY=$(hostname):0" this part,

**Comment by jwindhager** [comment]
Ah, my bad, you're on a Mac, not on Linux. Apologies! Please indeed use `DISPLAY=$(hostname):0`.

**Comment by sailseem** [comment]
Well, after i re-install everything, I finally can make this run!!! Thank you so much for your help and also your patience! 
One more question, so I can choose either ilastik-cell profiler or Deepcell segmentation to get the intensity of each marker. Either method should be fine, no need to combined them all, right?
Thanks!!!

**Comment by jwindhager** [comment]
Glad it works now! To answer your question: at this point, I cannot really think of situations in which you'd like to combine both Ilastik/CellProfiler and DeepCell *for nuclear segmentation*. But it's science after all, so I wouldn't be surprised if there was a use case for this at some point ;-)
