### ISSUE TITLE
What analysis can generate the file Pixel_classifier.ilp[

### ISSUE THREAD

**Issue by DrLGB** [BodenmillerGroup/steinbock#114]
What analysis can generate the file Pixel_classifier.ilp[
pixel_classifier.ilp](https://github.com/BodenmillerGroup/steinbock/blob/main/steinbock/classification/ilastik/data/pixel_classifier.ilp)

**Comment by jwindhager** [comment]
Please refer to the [documentation](https://bodenmillergroup.github.io/steinbock/latest/) or our [preprint](https://www.biorxiv.org/content/10.1101/2021.11.12.468357v1)
