### ISSUE TITLE
Error when building image from Dockerfile

### ISSUE THREAD

**Issue by Emberwhirl** [BodenmillerGroup/steinbock#121]
Hi. 

Since I do not have a stable connection to GitHub Package Repository, I forked the repository and tried to build the steinbock docker image from Dockerfile. I then encountered an rpc error and failed to build the image. 

I attached the log file below. Any suggestions would be appreciated.

```
==========================================
[fetch stage begin.]
clone from remote repository: https://github.com/Emberwhirl/steinbock.git, branch: main
Cloning into '/workspace'...
commit info: * main 548ccf6 [origin/main] v0.13.5
[fetch successfully, takes 2s.]
==========================================
[ build stage begin.]
Building Artifact: xxxxxx/steinbock:v0.13.5
#1 [internal] load build definition from Dockerfile
#1 sha256:3e2b9cadb15e9aa48622ce531b55b64caedde0b4cae84cfbba6feb58b4a94d7e
#1 transferring dockerfile: 3.66kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:309f050db59bc5f6999d83f0bb7925cd2fd0b9747b50c6196b0df1d444a2951e
#2 transferring context: 2.30kB done
#2 DONE 0.0s
Dockerfile:80
--------------------
78 | COPY conftest.py MANIFEST.in pyproject.toml setup.cfg setup.py /app/steinbock/
79 | COPY steinbock /app/steinbock/steinbock/
80 | >>> RUN --mount=source=.git,target=/app/steinbock/.git SETUPTOOLS_SCM_PRETEND_VERSION="${STEINBOCK_VERSION#v}" pip install --no-deps -e "/app/steinbock[all]"
81 |
82 | COPY entrypoint.sh /app/entrypoint.sh
--------------------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 80: Unknown flag: mount
Build artifact xxxxxx/steinbock:v0.13.5 fail: "exit status 1"
[build failed, takes 0s.]
```

**Comment by jwindhager** [comment]
Hi @Emberwhirl, thanks for reaching out! For manually building the steinbock Docker image, you will need to [enable BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/). I hope this helps, please close this issue if it does.

**Comment by jwindhager** [comment]
Actually, probably good to leave this issue open as a reminder to document this.

**Comment by Emberwhirl** [comment]
> Hi @Emberwhirl, thanks for reaching out! For manually building the steinbock Docker image, you will need to [enable BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/). I hope this helps, please close this issue if it does.

Thank you for the swift reply! I will give it a try.
