### ISSUE TITLE
Reproducibility across releases

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/steinbock#130]
Hi @jwindhager 

again, this is more to track this issue rather than a real "issue". I have now run steinbock twice each using `v0.13.5` and `v0.14.1`. Using the same version I can recover exactly the same cells (at least the number of cells match) but I do get different numbers of cells when comparing between the different release. Do you know why this is and if that can be fixed somehow?
I'm using deepcell segmentation.

**Comment by jwindhager** [comment]
Hi @nilseling! Indeed, with steinbock v0.14.0, deepcell was upgraded from version 0.11.0 to 0.12.0 (see [here](https://bodenmillergroup.github.io/steinbock/latest/changelog/)), which included an update of the trained models (see [here](https://github.com/vanvalenlab/deepcell-tf/releases/tag/0.12.0)). I'm afraid there is no way to recover the same number of cells across versions, but you can always use multiple versions for the individual steps.
