### ISSUE TITLE
automatically detect uint type in io.py

### ISSUE THREAD

**Issue by jinyancool** [BodenmillerGroup/steinbock#131]
Hello,
In the io.py, I saw follow code:
mask_dtype = np.dtype(os.environ.get("STEINBOCK_MASK_DTYPE", "uint16"))

This let me cannot process uint32 images. When I change the code to uint32, it works.
mask_dtype = np.dtype(os.environ.get("STEINBOCK_MASK_DTYPE", "uint32"))

Is it possible automatically detect uint type in io.py? No need to do it manually.

**Comment by jwindhager** [comment]
Currently traveling, will reply early next week

**Comment by jwindhager** [comment]
Hi @jinyancool and @mjseignon, thanks for reaching out!

Indeed, per the [specification](https://bodenmillergroup.github.io/steinbock/latest/file-types/#object-masks), only 16-bit masks are supported at this moment. As you correctly point out, @mjseignon, this may be problematic for large masks containing more than `2^16 - 1 = 65535` cells. In such situations, you can run the steinbock Docker container with `-e STEINBOCK_MASK_DTYPE=uint32`, for example as shown in https://github.com/BodenmillerGroup/steinbock/issues/132. However, please note that this is considered a "hack" and not sufficiently tested at this point (although I do not expect major problems with this).

Hope this helps, please do not hesitate to reopen the issue if anything is unclear!

**Comment by jwindhager** [comment]
Hi @mjseignon 

> I'm assuming calling this flag with `uint32` is the same as the the np.float32 added in the latest commits,` imagej=mask.dtype in (np.uint8, np.uint16, np.float32)`

No. Specifying `-e STEINBOCK_MASK_DTYPE=uint32` instructs steinbock to always read/write masks as 32 bit unsigned integer images. This is not directly related to the latest commits.

What you are referring to is a bugfix to avoid saving images in ImageJ format when the data type is not supported (the ImageJ format only supports uint8, uint16 and float32, see [here](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L1350-L1351)). For example, masks that are written as uint32 (e.g., when specifying `-e STEINBOCK_MASK_DTYPE=uint32`) won't be written in ImageJ format.
