### ISSUE TITLE
Steinbock issue with starting ilastik

### ISSUE THREAD

**Issue by StiThor** [BodenmillerGroup/steinbock#137]
Hi,

Running Steinbock on windows getting this error message:
![image](https://user-images.githubusercontent.com/90035897/184843564-4ad35906-142f-4d68-940b-b2f48cabb253.png) 
How can I solve this?

Best,
Stian

**Comment by jwindhager** [comment]
Commands that launch a graphical user interface (e.g. for Ilastik, CellProfiler) do not work on Windows hosts, see [docs](https://bodenmillergroup.github.io/steinbock/latest/install-docker/#windows)

**Comment by StiThor** [comment]
Would it be possible to run the graphical user interface on windows with for example Ubuntu?

**Comment by jwindhager** [comment]
You could theoretically run steinbock within a Ubuntu VM on a Windows machine, yes. However, please note the recommendation in the [docs](https://bodenmillergroup.github.io/steinbock/latest/install-docker/#windows):

> Commands that launch a graphical user interface (e.g. for Ilastik, CellProfiler) will not work on Windows hosts. It is recommended to run these programs directly on the Windows host, if graphical user interfaces are required. For compatibility, versions of third-party applications can be found in the [steinbock Dockerfile](https://github.com/BodenmillerGroup/steinbock/blob/main/Dockerfile).

**Comment by StiThor** [comment]
Okei :) Why won`t the program find the .mcd file when the directory is correct?
![image](https://user-images.githubusercontent.com/90035897/184872611-8049e3f3-74b1-4eb6-b29e-ca5161183e9a.png)

**Comment by jwindhager** [comment]
Could you please post your `steinbock` alias (the doskey command) here?
