### ISSUE TITLE
Using 'postprocess_kwargs=' with steinbock deepcell segment?

### ISSUE THREAD

**Issue by Pancreas-Pratik** [BodenmillerGroup/steinbock#138]
Hello,

How would I use the following line/argument correctly:
`steinbock segment deepcell **postprocess_kwargs={'interior_threshold': 0.2}** --minmax -o masks_deepcell`

I am specifically trying to use the argument`postprocess_kwargs_whole_cell={'interior_threshold': }`. I end up with no masks:

```
updating: intensities/ (stored 0%)
updating: masks_deepcell/ (stored 0%)
updating: neighbors/ (stored 0%)
updating: ome/ (stored 0%)
```

The reason I would like to use this is to deselect segemented background. Deepcell Mesmer is counting a little bit of background as nuclei/cells in IMC.

Thank you for your work into steinbock and in advance for your help! : )

**Comment by jwindhager** [comment]
Hi @Pancreas-Pratik, thank you for reaching out and apologies for the lack of documentation about this!

As with every steinbock command, help is available with the `--help` option:
```
> steinbock segment deepcell --help
Usage: steinbock segment deepcell [OPTIONS]

  Run a object segmentation batch using DeepCell

Options:
  --app [mesmer]               DeepCell application name  [default: mesmer]
  --model TEXT                 Path/name of custom Keras model  [default:
                               MultiplexSegmentation]
  --modeldir DIRECTORY         Path to Keras model directory  [default:
                               /opt/keras/models]
  --img DIRECTORY              Path to the image directory  [default: img]
  --minmax / --no-minmax       Channel-wise min-max normalization  [default:
                               no-minmax]
  --zscore / --no-zscore       Channel-wise z-score normalization  [default:
                               no-zscore]
  --panel FILE                 Path to the panel file  [default: panel.csv]
  --aggr TEXT                  Numpy function for aggregating channel pixels
                               [default: mean]
  --pixelsize FLOAT            [Mesmer] Pixel size in micrometers  [default:
                               1.0]
  --type [whole-cell|nuclear]  [Mesmer] Segmentation type  [default: whole-
                               cell]
  --preprocess FILE            [Mesmer] Preprocessing parameters (YAML file)
  --postprocess FILE           [Mesmer] Postprocessing parameters (YAML file)
  -o DIRECTORY                 Path to the mask output directory  [default:
                               masks]
  -v, --verbosity LVL          Either CRITICAL, ERROR, WARNING, INFO or DEBUG
  --help                       Show this message and exit.
```

As indicated in the options list, you can use the `--postprocess` command line option to specify a YAML file containing the postprocessing parameters for the Mesmer model, for example as follows:
```
steinbock segment deepcell --postprocess deepcell_postprocessing.yml ...
```

In your example, the contents of `deepcell_postprocessing.yml` would look like the following (not tested):

```yaml
interior_threshold: 0.2
```

Hope this helps, please let me know if this works for you! Also, I'll keep this issue open as a reminder to better document this.

**Comment by Pancreas-Pratik** [comment]
@jwindhager I am so grateful to see your response! I was actually praying in my mind while driving to work (just arrived) that YOU (@jwindhager) would respond. I saw you responded to another post around 4:30am in June or July. Thank you again. Going to try this now : )

**Comment by Pancreas-Pratik** [comment]
@jwindhager I've spent like a couple hours on this now, only to find that I had been deleting the shared `singularity` cache and tmp directories everytime I ran the SLURM job script I was sending. I think this was the problem all along! It was me and not `steinbock`! It looks like it's running now (much longer than usual - good sign) I'll probably set singularity to keep all tmp and cache for it's own job/project in it's own working directory.

Sorry about that, and thank you again.

**Comment by Pancreas-Pratik** [comment]
Okay, so the real "issue" was, I think, that `deepcell` was not accepting anything other than, I guess, the default value of `0.2` for `postprocess_kwargs={'interior_threshold': 0.2}`. However the problem was really me! Because when I looked all of the segmentation from "a forest view" rather than "a tree view". It brought me inner joy, because it saved me weeks to maybe even months of my life (R.I.P. Ilastik crayolas with CellProfiler). You guys are rockstars!

Expect to see us citing your hardwork, hopefully soon ; )
