### ISSUE TITLE
Can't locate Ilastik

### ISSUE THREAD

**Issue by tryggest** [BodenmillerGroup/steinbock#143]
I am running Steinbock from my terminal on my Mac. Everything has work fine until I try to bath process the probabilities  created in Ilastik `steinbock classify ilastik run`

I then get the error `FileNotFoundError: [Errno 2] No such file or directory: ‘/opt/ilastik/run_ilastik.sh’`

(Steinbock is installed trough pip)

**Comment by jwindhager** [comment]
The steinbock Python package does not ship with third-party software - you'll have to install Ilastik & CellProfiler yourself and provide the path to the `run_ilastik.sh` file to the steinbock command via command line options, or, alternatively, use the steinbock Docker container (recommended)

**Comment by tryggest** [comment]
Thanks for the reply @jwindhager 

When I run the docker on my mac this error pops up:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/opt/ilastik/ilastik-meta/lazyflow/lazyflow/classifiers/__init__.py:20: UserWarning: init: Could not import tiktorch classifier
  warnings.warn("init: Could not import tiktorch classifier")
Starting ilastik from "/opt/ilastik".
QXcbConnection: Could not connect to display Annes.home:0
Fatal Python error: Aborted`

**Comment by jwindhager** [comment]
Unfortunately, as far as I know, the current stable version of Ilastik does not run on M1 platforms
