### ISSUE TITLE
[Help] ilastik batch process step cannot find `pixel_classifier.ilp`

### ISSUE THREAD

**Issue by Mr-Milk** [BodenmillerGroup/steinbock#145]
After training in ilastik, I ran the following command:
```shell
steinbock classify ilastik run --ilp pixel_classifier.ilp
```
However, it raises an Error:
```
Error: Invalid value for '--ilp': File 'pixel_classifier.ilp' does not exist.
```
If I list the files in the directory, I can see the ilastik project file is there
```
> ls
ilastik_crops  ilastik_img  ilastik_probabilities  pixel_classifier.ilp
```

**Comment by jwindhager** [comment]
Hi @Mr-Milk, could you please post your steinbock alias here? Thanks

**Comment by Mr-Milk** [comment]
Oh! The path should be relative to the path I mount to it. I forget that this is an alias command.
