### ISSUE TITLE
Steinbock container keeps exiting

### ISSUE THREAD

**Issue by cuiriouscancerscientist** [BodenmillerGroup/steinbock#149]
When I try to open the container in docker it says running then exits immediately (less than 1 second). Could you help me solve this issue?

**Comment by jwindhager** [comment]
Hi @cuiriouscancerscientist, thanks for reaching out.

What exactly do you mean by "open the container in docker"? Is there a specific command you are running?

**Comment by cuiriouscancerscientist** [comment]
Thank you, when I click "run" it will say running then exit immediately within a second.

**Comment by jwindhager** [comment]
Please note that the steinbock Docker container is operated using the command line. Steinbock does not ship with a graphical user interface, nor does it provide a "run" button of some sort.

**Comment by cuiriouscancerscientist** [comment]
I was trying to run it in docker. After I have the Steinbock container in docker I thought I had to click run to use the CLI in docker to use the steinbock pipeline. If that is incorrect could you explain what I should be doing instead, please?

**Comment by jwindhager** [comment]
Ah, now I was able follow, thanks for the clarifications! To run the steinbock Docker container, please open the command prompt (Windows) or shell (Linux/MacOS) and follow the [installation instructions](https://bodenmillergroup.github.io/steinbock/latest/install-docker/). For example, on MacOS/Linux, after installing prerequisites such as Docker, you would start by configuring a steinbock alias by typing the respective `alias...` command. The Docker Desktop user interface is not required to run steinbock.

**Comment by cuiriouscancerscientist** [comment]
![Capture](https://user-images.githubusercontent.com/114181640/192321301-7cded85b-a83f-41f5-a47c-25c5717ecda8.JPG)
Hello again,
I have followed the installation instructions however when I get to this command line "docker run -v "C:\Data":/data ghcr.io/bodenmillergroup/steinbock:0.15.0." I get the help text. 

More background: Following the steps I was able to successfully download docker and it seems to be working. I have the steinbock container on docker, which exits a second after I hit run. I have tried other containers e.g. alpine and it seems to run fine on docker. Once I am up to the aforementioned command line I have not been able to move beyond this step.

I am new to this so thank you for your patients.

**Comment by jwindhager** [comment]
> I have followed the installation instructions however when I get to this command line "docker run -v "C:\Data":/data ghcr.io/bodenmillergroup/steinbock:0.15.0." I get the help text.

This is perfectly normal and expected, since you do not specify a command (available commands are shown in the help text). Please follow the [installation instructions](https://bodenmillergroup.github.io/steinbock/latest/install-docker/#windows) to set up a `steinbock` command alias for the current session using `doskey`. As noted in the [usage instructions](https://bodenmillergroup.github.io/steinbock/latest/cli/intro/), this is a prerequisite for running the commands as documented online and in the help text.

**Comment by cuiriouscancerscientist** [comment]
Thank you!
