### ISSUE TITLE
AMD64

### ISSUE THREAD

**Issue by cuiriouscancerscientist** [BodenmillerGroup/steinbock#152]
Hi, I have a MacBook with the apple chip, and I keep getting the error "AMD64" when I try to run the container; I get this message in the mac terminal. 
<img width="565" alt="Screen Shot 2022-10-25 at 12 24 50 PM" src="https://user-images.githubusercontent.com/114181640/197841393-325662a6-89ae-47c1-a99f-14ba304c5bb4.png">

Could you help me with rectifying this error message?

Thank you.

**Comment by jwindhager** [comment]
Hi @cuiriouscancerscientist, the current version of steinbock does not support M1 platforms (see #98), sorry.
