### ISSUE TITLE
Inconsistent number of channels when using DeepCell/Mesmer segmentation

### ISSUE THREAD

**Issue by yiqiaochen7** [BodenmillerGroup/steinbock#163]
Hello, I was trying to run the pipeline with example data and when I entered "steinbock segment deepcell --app mesmer --minmax". It showed ValueError: Input data must have 2 channels. Input data only has 47 channels. It seems to work when I opened the "panel.csv" file in "steinbock new" folder and change the "keep" value from 1 to 0 for the first 46 rows (left the keep value as 1 for Pt196 and Pb206). Is it feasible? Would it affect the following results?

Best wishes,
Yiqiao

**Comment by jwindhager** [comment]
Hi @yiqiaochen7 

Some clarifications:
- The `keep` column specifies which channels are retained during image export, see [here](https://bodenmillergroup.github.io/steinbock/latest/file-types/) and [here](https://bodenmillergroup.github.io/steinbock/latest/cli/preprocessing/#imaging-mass-cytometry-imc). If there is no `keep` column present in the panel file, all channels will be retained. Do not alter the `keep` column after image preprocessing.
- The `deepcell` column determines nuclear (1) and cytoplasmic (2) channels, see [here](https://bodenmillergroup.github.io/steinbock/latest/file-types/) and [here](https://bodenmillergroup.github.io/steinbock/latest/cli/segmentation/#deepcell). DeepCell/Mesmer segmentation requires at least one channel marked as nuclear and at least one channel marked as cytoplasmic.

So, to solve your issue, please do not alter the `keep` column, but adapt the `deepcell` column instead. In case you are following the workshop material, a suitable panel file was provided with the example data, see [here](https://github.com/BodenmillerGroup/ImagingWorkshop2023/tree/main/data).

Hope this helps.

**Comment by yiqiaochen7** [comment]
Hi Jonas,

Thank you very much for the reply. It worked. May I ask one more question? Is there link introducing how to process my raw data (.mcd file) so that I can run it with the steinbock pipeline. Should I make it to zip? should I generate that panel.csv file?

Best wishes,
Yiqiao
________________________________

**Comment by jwindhager** [comment]
Please consult the [steinbock documentation](https://bodenmillergroup.github.io/steinbock/latest/cli/preprocessing/#imaging-mass-cytometry-imc)
