### ISSUE TITLE
Releasing 0.16.1 failed, build workflow potentially broken?

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/steinbock#187]
I today saw that not all variants are available on GHCR for the 0.16.1 release. Checking GitHub Actions, it seems that the build workflow failed (see [attempt 1](https://github.com/BodenmillerGroup/steinbock/actions/runs/4914612927/attempts/1)). I tried re-running the failed jobs (see [attempt 2](https://github.com/BodenmillerGroup/steinbock/actions/runs/4914612927/attempts/2)), but it doesn't seem to resolve the issue.

**Comment by Milad4849** [comment]
Looking [here](https://github.com/BodenmillerGroup/steinbock/actions/runs/4914612927/jobs/8957510913#step:7:930) it appears to be a connectivity issue, will check in some hours.

**Comment by Milad4849** [comment]
So after failing and throwing a variety of errors over multiple runs, it now passes. I did not really get what was causing the fails.
