### ISSUE TITLE
Mask signal discordance

### ISSUE THREAD

**Issue by megleila** [BodenmillerGroup/steinbock#223]
There is a significant discordance between visually what I am seeing for marker expression in the raw data (ie using MCD viewer) and the expression mapped onto masks using imcRtools -- not just for one marker but for many. Can you help me understand why this is?  Is this expected or a sign something is incorrect?

<img width="1067" alt="image" src="https://github.com/BodenmillerGroup/steinbock/assets/135244025/f7e8ba86-f2aa-4a9d-aaa1-f43ef0e5080e">
<img width="1067" alt="image" src="https://github.com/BodenmillerGroup/steinbock/assets/135244025/9b442139-0900-4522-a16b-e6162e68128f">

<img width="1067" alt="image" src="https://github.com/BodenmillerGroup/steinbock/assets/135244025/43d011ab-453c-42ee-b9c3-7b184a81cadf">
<img width="1067" alt="image" src="https://github.com/BodenmillerGroup/steinbock/assets/135244025/b586dbcb-27ad-4f8d-bf5b-61d19c114788">

<img width="1067" alt="image" src="https://github.com/BodenmillerGroup/steinbock/assets/135244025/d4e6a43a-10be-4757-98e9-b07d1e7262cc">
<img width="1067" alt="image" src="https://github.com/BodenmillerGroup/steinbock/assets/135244025/7b0968b4-a830-4ed4-8857-897e749b0c2a">

**Comment by nilseling** [comment]
Hi @megleila 

Could you please explain what you have done to process the data? Could you also potentially share the data and the scripts with me (nils.eling@uzh.ch).

**Comment by nilseling** [comment]
So I'm seeing that for "Batch1_002" there are 6808 cells in the corresponding intensities CSV. However there are only 6299 cells in the cell mask TIFF. Something didn't work right when you applied steinbock to the data. Please redo the processing and test this again. My assumption is that you calculated the intensities, etc on different masks.

**Comment by nilseling** [comment]
It can also help to open the CSV files in Excel and the masks in FIJI (click Image > Adjust > Brightness and Contrast to observe the maximum cell ID) and compare.

**Comment by megleila** [comment]
That's weird.  I'll definitely re-process it and try again.  Thank you so much!
________________________________

**Comment by megleila** [comment]
This fixed it - not sure what happened before.  Thanks for that catch and for your help!

**Comment by nilseling** [comment]
That's great, I'm glad it worked. I'm closing this now.
