### ISSUE TITLE
Hot pixel filter issue

### ISSUE THREAD

**Issue by giuliospinozzi** [BodenmillerGroup/steinbock#224]
Hi, I don’t understand the logic of Hot pixel filter in Steinbock. The default value is 50, but is it a percentage? To increase the threshold I should increase the value? The maximum is 100?
I tried with —hpf 25, 30, 50, 60, 80 and the situation of hot pixels in napari (opening the stacked image in /img folder) is the same. I would like to know which is the limit of hpf…

**Comment by Milad4849** [comment]
Hi @giuliospinozzi, 
Thanks for reaching out. That value is a threshold for pixel intensity. The hot pixel fix would be applied to pixels with intensity above this value. What do you mean by 'situation of hot pixels in napari is the same'? If you are inspecting the outcome by eye, that is not really informative, you have to compare the intensity values to see whether they are changed after hot pixel fixing.

**Comment by Milad4849** [comment]
@giuliospinozzi, if there is not follow up, could you please close this issue?
