### ISSUE TITLE
Error: No panel/.mcd/.txt file found

### ISSUE THREAD

**Issue by icepsi23** [BodenmillerGroup/steinbock#242]
I'm using this example to run steinbock: https://bodenmillergroup.github.io/IMCDataAnalysis/prerequisites.html 

I'm at:
# raw data preprocessing
steinbock preprocess imc panel --namecol Clean_Target

After  running that line I got the: Error: No panel/.mcd/.txt file found

Any advise on how I can fix this problem? I'm new at using a docker and new to analyzing IMC data.

<img width="878" alt="Screenshot 2024-02-13 at 10 39 45 AM" src="https://github.com/BodenmillerGroup/steinbock/assets/118706141/0e9b992d-aab8-4e69-88e2-c95d8233d1fa">

**Comment by Milad4849** [comment]
Hi @icepsi23 

It appears that you are missing some files or that they are not in the expected location. Please check that you have the necessary files at expected locations, as specified [here](https://bodenmillergroup.github.io/steinbock/latest/directories/). If you execute all commands in 4.3 successfully, that should be the case, therefore make sure all commands in 4.3 up the error causing line are executed successfully.

**Comment by icepsi23** [comment]
I actually have the panel file on the folder, and have run successfully run the 4.3 section successfully. 

<img width="641" alt="Screenshot 2024-02-14 at 8 03 33 AM" src="https://github.com/BodenmillerGroup/steinbock/assets/118706141/e02989ad-7394-4983-9d06-274b53d2d67a">

**Comment by Milad4849** [comment]
In that case I am afraid your error is not reproducible, I ran 4.3 from scratch and everything works fine. Is the above the content of your `raw` folder? You can try to provide the path(s) to the relevant files explicitly:
![image](https://github.com/BodenmillerGroup/steinbock/assets/70942846/7da24ad7-d048-45ed-9eb1-65cb2f3c81e8)

**Comment by icepsi23** [comment]
Yes, the above is my raw folder. I figure out the problem was the linux support software that I was using. Thank you for your help.
