### ISSUE TITLE
preprocess imc panel Error

### ISSUE THREAD

**Issue by LukasHats** [BodenmillerGroup/steinbock#248]
I am currently trying to create a panel file using `preprocess imc panel `. However, it does say, that it can't find any .mcd or .txt files. Although they should be definitely there:

```
lukashat@dhcp132b Myeloma > alias steinbock="docker run -v ~/Documents/PhD_Schapiro/Projects/Myeloma/raw:/data --platform linux/amd64 -u $(id -u):$(id -g) -p 8888:8888 ghcr.io/bodenmillergroup/steinbock:0.16.1"

lukashat@dhcp132b Myeloma> steinbock preprocess imc panel
Error: No panel/.mcd/.txt file found

lukashat@dhcp132b Myeloma> ls ~/Documents/PhD_Schapiro/Projects/Myeloma/raw
XXX_IMC01_UB.mcd		XXX_IMC01_UB_ROI_1.txt	XXX_IMC01_UB_ROI_2.txt
```

I also ran the docker container with bash:
```
lukashat@dhcp132b Myeloma > docker run -it -v ~/Documents/PhD_Schapiro/Projects/Myeloma/raw:/data --platform linux/amd64 -u $(id -u):$(id -g) --entrypoint /bin/bash ghcr.io/bodenmillergroup/steinbock:0.16.1


________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


You are running this container as user with ID 501 and group 20,
which should map to the ID and group for your user on the Docker host. Great!

tf-docker /data > ls
XXX_IMC01_UB.mcd  XXX_IMC01_UB_ROI_1.txt  XXX_IMC01_UB_ROI_2.txt
```

I am running it on a M3 MacBook. Might that be the issue with the docker container? As mentioned [here](https://bodenmillergroup.github.io/steinbock/latest/install-docker/)

**Comment by Milad4849** [comment]
Hi @LukasHats 
We would appreciate it if you first look in the documentation for solution to your problems before posting an issue.  Under [directories](https://bodenmillergroup.github.io/steinbock/latest/directories/) you will see that your root folder is supposed to be one above raw. Also in the documentation you can see how to explicitly specify your panel and mcd files when they are not located in the default location.

**Comment by LukasHats** [comment]
Thanks for taking the time!
