### ISSUE TITLE
Unable to find image 'preprocess:latest' locally error

### ISSUE THREAD

**Issue by MAvdB-KCL** [BodenmillerGroup/steinbock#251]
I'm trying to preprocess some MCD/TXT files into TIFs, but am having trouble extracting the panel.csv or the TIFs. 

Hardware: 
The machine I'm running it on is an iMac running Ventura 13.6.6 with 16 GB RAM. 

Issue:

- I have the MCD/TXT files inside a steinbock>raw folder structure.
- I have Docker open and running (v4.28.0).
- In Terminal I'm attempting to set up an alias:

alias steinbock="docker run -v "/Folder/steinbock":/data --platform linux/amd64 -u $(id -u):$(id -g) -p 8888:8888 -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/home/steinbock/.Xauthority:ro -e DISPLAY=host.docker.internal:0 ghcr.io/bodenmillergroup/steinbock:0.16.1"

- When attempting to check the Steinbock version using (steinbock --version) I get an error "unknown flag: --version"
- When attempting to extract the panel file or TIFs respectively...

steinbock preprocess imc panel --unzip
steinbock preprocess imc images --unzip --hpf 50 

...I get this error:

Unable to find image 'preprocess:latest' locally
docker: Error response from daemon: pull access denied for preprocess, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

- In the past I've managed to get this to work using Steinbock version 0.15.0 using the same folder structure, but now I can't seem to get it to work. 

BodenmillerGroup run --help...please!

**Comment by Milad4849** [comment]
Hi, 
I cannot reproduce your issue, the alias command, as specified in the documentation, works fine on Macs. Your issues is not due to steinbock, it seems related to your docker set-up. As such it is not within the scope of what we address here.
