### ISSUE TITLE
issue of Segmentation fault

### ISSUE THREAD

**Issue by dingxm** [BodenmillerGroup/steinbock#252]
I have a big tiff (19755x14552 ) for the segmentation.
I met issue of "out of memory".  I have 1Tb memory for my Linux server.
Below is the error info:
/app/entrypoint.sh: line 3:    13 Segmentation fault      (core dumped) python -m steinbock "$@"
Is there anyway I can change some parameter that the deepcell step will use less memory. For example change the number of thread.
Thanks

**Comment by Milad4849** [comment]
Hi @dingxm 
You cannot specify such a parameter via steinbock. I think your best bet is to try deepcell tiling directly (not via steinbock). Steinbock is primarily designed to handle imc images and not images of the size that you have.
