### ISSUE TITLE
1 really poor, but essential, marker with extremely high background

### ISSUE THREAD

**Issue by FelixShore1** [BodenmillerGroup/steinbock#254]
Hi all,

So I have collected some data and upon inspection, it seems that one of our normally very "safe bet" antibodies seems to have stained extremely poorly. 

On MCD viewer, I can turn down the threshold max and you can see the real staining, but there is a huge amount of far brighter background.
![image](https://github.com/BodenmillerGroup/steinbock/assets/167977680/590cebb9-3188-466f-891a-424e6deece67).

This is a marker we really need and unfortunately, we dont have any more serial sections to restain a new antibody to detect this.

I am therefore wondering whether I can take the images from the img folder and somehow correct the images slightly. I started having a play in Fiji. In Fiji, when the image first opens, you cant really see anything (the same with nearly all images), but when I adjust the brightness/contrast and min/max I can see the image. 

![image](https://github.com/BodenmillerGroup/steinbock/assets/167977680/9ae6a61f-cfc8-4213-a247-4702c5681e73)

If I then 'despeckle' the image (just the first channel, containing the dodgy marker), I can start to pick out the staining quite nicely.

![image](https://github.com/BodenmillerGroup/steinbock/assets/167977680/fdd4a7f5-485d-4e22-a2fe-039ae8f674d9)

However, at this point, I have obviously played with the brightness/contrast values and theyre now super high. Should I reset the values back to their original values (just with far less of the speckling). Or should I slightly boost the values so that the marker is not as weak as previously.

I would really appreciate some help here as I am running myself in circles and really need to get something from this marker.
Does what I have done work? Is there a different/better way to do this? any changes to the above method?
Thanks so much.

Best wishes,

Felix

**Comment by Milad4849** [comment]
Hi @FelixShore1 

Here we address issues that are directly related to the use of the package steinbock. What you have posted above falls entirely out of that scope and as such cannot be addressed here.
