### ISSUE TITLE
Different signal intensities for the same ROI 

### ISSUE THREAD

**Issue by yasrod** [BodenmillerGroup/steinbock#269]
Hi, I performed the steinbock pipeline first with the mcd-file and then only with the txt-file for the same ROI. I figured out that the signal intensities (Folder: Steinbock/intensities/csv-file) are not identical. The values slightly differ. For instance - 0,8309285725866046 compared to 0,8308824471064976. 
Is there any explanation why the values of the same ROI differ depeding if one takes the mcd- or txt-file?
Thanks in advance!

**Comment by Milad4849** [comment]
Hi, this does not appear to be related to steinbock. The mcd and txt files simply have different values in them.

**Comment by yasrod** [comment]
Thanks for your answer, But is there are reason why mcd- and txt-file have different values for the same ROI?

**Comment by Milad4849** [comment]
I don't know, that would require knowledge of the innerworkings of the machine's software. my understanding is that this level of discrepancies do not actually impact the results and therefore we had not had an issue. I think this would be a good issue to bring up to the manufacturer of the machine though :)

**Comment by yasrod** [comment]
Thanks a lot for your answer! We also had not had any issue with the values, but just were curious. Yes, I also asked the manufacturer :)
