### ISSUE TITLE
Include napari in Docker container

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/steinbock#27]

**Comment by jwindhager** [comment]
This would require integrating OpenGL into the Docker image (e.g., via nvidia-docker) and would therefore be to restrictive

**Comment by VolkerH** [comment]
Only came across this project now (seems we're doing very similar stuff).
In our group we're also packaging everything into Docker containers, and we do include napari.
Maybe this is useful: https://github.com/VolkerH/Jupyter-Napari-Desktop
