### ISSUE TITLE
Measure intensities of user-defined loci

### ISSUE THREAD

**Issue by Shhsvri** [BodenmillerGroup/steinbock#270]
I am working on skin tissue samples. I am using steinbock with deepcell. I was wondering if there is  functionality to measure intensities by user defined borders? My goal is to measure intensities in the epidermis and compare with signal from the dermis.

**Comment by Milad4849** [comment]
@Shhsvri 
Steinbock operates on segmented objects. You would have to make segmented objects out of whatever you want to quantify the signal based on. If what you are interested in are not cells, then you likely have to find another way, such as training a model via ilastik, to achieve your desired segmentation.
