### ISSUE TITLE
Improve IMC Segmentation Pipeline panel support

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/steinbock#38]
Allow duplicated metal tags (combine targets with separator to form channel name) and targets shared among different metal tags (add metal tag as suffix to channel name)

**Comment by nilseling** [comment]
Hmm, why do you want to combine targets that have different metal tags? I'd say to keep the metal tag as main id, not caring what the target is.

**Comment by jwindhager** [comment]
Not planning on combining targets with different metal tags

**Comment by nilseling** [comment]
All good now
