### ISSUE TITLE
Support for histoCAT image/folder generation

### ISSUE THREAD

**Issue by a-rayford** [BodenmillerGroup/steinbock#62]
For those of us migrating to Steinbock from the IMCPreprocessingPipeline, it is still common to check the quality of the segmentation/single-cell data by loading the masks/images into histoCAT. So far I have not seen a command in the CLI usage to generate histoCAT-compatible folders, and have had to use the code in the old IMCPreprocessing jupyter notebook script to accomplish this (with a bit of tweaking since the directory structure has changed). Would it be possible to add a command within the Docker implementation that does this?

**Comment by jwindhager** [comment]
steinbock v0.9.0 now supports a `steinbock export histocat` command, see https://bodenmillergroup.github.io/steinbock/latest/cli/export/#histocat
