### ISSUE TITLE
Add panel metadata to AnnData export

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/steinbock#66]
... as variable annotations, as suggested by @ndamond

**Comment by jwindhager** [comment]
Unfortunately, `anndata` currently does not support pandas' nullable data types (see https://github.com/theislab/anndata/issues/628), which are required for panel/image metadata.

**Comment by ivirshup** [comment]
https://github.com/theislab/anndata/issues/504 may be a better issue to track here

**Comment by jwindhager** [comment]
While nullable ints/bools are now supported, pandas StringArray support (for nullable string columns) is still missing: https://github.com/scverse/anndata/issues/679

**Comment by ivirshup** [comment]
@jwindhager how strong is your need for strings instead of categoricals? E.g. will you have repeated values in these columns?

**Comment by jwindhager** [comment]
Thanks for checking in @ivirshup! Unfortunately, these cannot be expected to be categoricals. I'm currently implementing a workaround based on `astype(str)` (i.e., convert `dtype("string")` columns to `dtype("O")`) and leave it up to anndata to deal with it (I assume you're internally converting to categoricals - not the most efficient way I assume, but currently a good enough workaround I guess).
