### ISSUE TITLE
CellProfiler error during SaveImages (within Docker): Images of type float must be between -1 and 1

### ISSUE THREAD

**Issue by a-rayford** [BodenmillerGroup/steinbock#75]
Hi again, 

I have had issues with CellProfiler saving images, both multichannel and single-channel tiffs. Each time I get the error "Images of type float must be between -1 and 1". I can't seem to find much help for this online, and I have the settings for NamesAndTypes and SaveImages exactly as they are in 3_measure_mask_basic.ccpipe from the IMCPreprocessingPipeline (CP4_pipelines). 

I made a CellProfiler project within Docker that simply loads all the multichannel tiffs from the data/img folder and tries to save them (in data/test), and I get the error. I can't seem to attach the .ccproj file but I put screenshots of the settings below. Can you reproduce this and if so, is there something I'm doing wrong? I get a similar error when using CellProfiler locally. 

From NamesAndTypes:
![image](https://user-images.githubusercontent.com/44172212/139209006-c154f01f-e61f-4513-a189-c2e991ef16ae.png)

From SaveImages:
![image](https://user-images.githubusercontent.com/44172212/139209098-46e14758-5fb7-4cc0-86e5-feb24b322f89.png)

Error Message:
![image](https://user-images.githubusercontent.com/44172212/139209219-5c063b4d-7f14-4046-b184-b7ae406542ac.png)

Thanks again for your help!
-austin

**Comment by a-rayford** [comment]
Hi Vito,

Thanks for this, I was able to save the distance image as a tiff after rescaling by 1/65565 using ImageMath. However, applying the same ImageMath function to the FullStack (multichannel) IMC image (loaded from the steinbock/img folder, also has issues with -1 to 1 range when I simply try to load/resave it in CP) only works when I turn the "eye" off for that step. Combining the scaled distance image and the scaled FullStack image using StackImages does not produce an error but the resulting saved tiff (regardless of 8- 16- or 32-bit floating integer) is not the correct dimensions (too skinny) and has 365 channels instead of ~30. I'm not sure if I'm doing something wrong in CellProfiler or if these set of commands just won't work when starting with a multichannel image.

The original goal was to add the distance image as a channel to the IMC image stack so they could all be measured simultaneously using `steinbock measure intensities`. Since I currently can only save the distance images alone and not the full stack, I tried to measure them independently by swapping them with the full stack IMC tiffs in the steinbock/img folder. When I try to measure these distance images I get the following error for each ROI/.tiff in the img folder:

`Error measuring intensities in img/9_HCC827-SV80_HCC827-SV80_5_6.tiff
Traceback (most recent call last):
  File "/app/steinbock/steinbock/measurement/intensities.py", line 57, in try_measure_intensities_from_disk
    intensities = measure_intensites(
  File "/app/steinbock/steinbock/measurement/intensities.py", line 37, in measure_intensites
    data = {
  File "/app/steinbock/steinbock/measurement/intensities.py", line 39, in <dictcomp>
    img[i], labels=mask, index=object_ids
IndexError: index 1 is out of bounds for axis 0 with size 1`

Any idea what this error means? Does `steinbock measure intensities` have any other dependencies besides the tiffs in the masks and img folder? The names of the distance .tiff files are identical to the multipage IMC tiffs that I swapped out in the img folder.

I know that this is a rather specific issue, however I think that it will be useful to work out these kinks with distance transforms within Steinbock since this is a common goal in many pipelines to measure distances to binary tissue compartment masks. -austin

**Comment by jwindhager** [comment]
Hi @a-rayford

just to keep you in the loop: I'm currently fixing some issues with steinbock (new release expected for today or tomorrow). Not sure these are related to this issue, but I will look into it tomorrow the latest. Apologies for the delay and thanks for the patience :)

Cheers

**Comment by a-rayford** [comment]
Hi Jonas,

No rush, just wanted to follow up with how far I got on this until I got stuck again. Looking forward to the new release. :) -austin

**Comment by jwindhager** [comment]
Hi @a-rayford, apologies again for the delay. Just released v0.10.0, which should at least (probably) fix the issue of loading images in cellprofiler after `steinbock measure cellprofiler prepare`. Will try to reproduce your pipeline and take care of the rest next week. Have a good weekend!

**Comment by jwindhager** [comment]
Assuming this issue to be resolved - please reopen if not! Thanks

**Comment by a-rayford** [comment]
I fixed this issue via a workaround in CellProfiler as follows:

- import the multipage tiffs from the img folder as "FullStack"
- split the FullStack image into channels using ColorToGray (total 28 channels)
- reassemble them with GrayToColor (while also adding my distance transform image as an additional channel at the end, no need to rescale) 
- save the resulting "ColorImage" as 32 bit floating-point with SaveImages
- Add an additional row to panel.csv with (Channel = Pu239 (arbitrary value), Marker = Border_Distance, Keep = 1)
- Run `steinbock measure intensities`, on the output files (rename output folder to "img")
- mean border distance is calculated as additional channel measurement for each cell

See CellProfiler issue [#4495](https://github.com/CellProfiler/CellProfiler/issues/4495) and [#4496](https://github.com/CellProfiler/CellProfiler/issues/4496). Potentially more flexible workaround using image metadata to come.
