### ISSUE TITLE
Steinbock workshop or tutorial?

### ISSUE THREAD

**Issue by veenstje** [BodenmillerGroup/steinbock#80]
Hello, 
First and foremost, thank you to the team for developing this important tool and pipeline for IMC data analysis. I'm wondering if there is any type of workshop, tutorial, or detailed manual on the use of Steinbock along with other components of the pipeline apart from what is currently documented in the repository and through the manuscript available at https://www.biorxiv.org/content/10.1101/2021.11.12.468357v1.full.  Unfortunately, as a coding novice it is incredibly daunting to try to use Steinbock without having someone to demonstrate the process. If there is no such resource yet available, is one planned in the near future?

Thank you!

**Comment by jwindhager** [comment]
Hi @veenstje 

Thank you for your interest in steinbock and our manuscript!

As both steinbock and imcRtools are relatively now, there aren't any further resources available online at this point beyond the steinbock documentation and the preprint. We expect that this will change over the coming months, for which the final publication, presentations and workshops are in the making. Links to any such online material will be added to the steinbock documentation. Please feel free to [reach out via email](mailto:jonas.windhager@uzh.ch) and I'll gladly keep you posted about any resources that may come up.

FYI, although it's probably not what you are looking for, @nilseling will give a short talk on the preprint at this event: https://app.livestorm.co/front-line-genomics/single-cell-and-spatial-omics-online-advanced-single-cell-technologies-and-optimising-the-workflow?type=detailed

In the meantime, we're happy to assist with any technical issues that may come up during setup or usage. I understand that multiplexed image processing can be a daunting task, and we've tried our best to make the tools as easy to use as possible. Please note that no coding is required to use steinbock - everything can be run through the command line (Linux/MacOS) or the command prompt (Windows). Installation instructions are available [here](https://bodenmillergroup.github.io/steinbock/latest/install-docker/) and usage instructions are available [here](https://bodenmillergroup.github.io/steinbock/latest/cli/intro/).
