### ISSUE TITLE
steinbock v0.10.0 re-downloads mesmer segmentation model

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/steinbock#82]
As reported by https://github.com/JhuangLab  via email, `steinbock segment deepcell` always re-downloads the Mesmer segmentation model. This is a problem when running steinbock offline and should be fixed asap.

**Comment by jinyancool** [comment]
Thank you for your help.

**Comment by jwindhager** [comment]
Could not reproduce this issue. The original report was related to the steinbock Python package (which does not ship with third-party stuff), not the steinbock Docker container. Detailed explanations were given in the email response.
