### ISSUE TITLE
Fix panel.csv in steinbock preprocess imc panel (from .txt), multiple rows per channel + column name incompatibility w/ CATALYST

### ISSUE THREAD

**Issue by a-rayford** [BodenmillerGroup/steinbock#96]
Hi, I have been using v0.9.1 (in Docker) consistently for my dataset, and it's been running smoothly without issues. In R, I imported the measurements (e.g. intensities/regionprops) made by steinbock as a SingleCellExperiment using read_steinbock (imcRtools) in order to make scatter plots using CATALYST. However, when I tried to run plotScatter I kept getting "Error: subscript contains invalid names"

A lot of head-scratching and googling later... I found out that the first two rowData columns must have specific names: "channel_name" and "marker_name" in order for plotScatter to work. Thus I fixed the issue myself in R, but I was hoping these suffixes could be implemented in the auto-generated panel.csv column names (or alternatively include a chunk of R code in the documentation of imcRtools to fix the rowData names) so that other users don't have to go through the same process I did to get plotScatter to work. I'm not sure how many people would want to use this function, but it seems like an obvious thing to do (with a not-so-obvious solution) when the data is already imported as SingleCellExperiment and there aren't (to my knowledge) any built-in functions within cytomapper/imcRtools to make scatterplots of cell marker intensities (at least for multiple ROIs).

Secondly, I updated Steinbock to v0.12.0 just to see if these column names had already been updated before logging this issue. When I made the panel.csv file using steinbock preprocess imc panel (from .txt files since I am only analyzing a subset of ROIs from the mcd file), there were duplicate rows for each marker per ROI (e.g. aSMA 1, aSMA 2, .... aSMA [# of ROIs]). I switched back to 0.9.1 to confirm that steinbock preprocess imc panel is indeed still working correctly with the data. I think that the issue is specific to using exclusively .txt files. Thanks for your support!

**Comment by nilseling** [comment]
Hi @a-rayford 

the `SingleCellExperiment` class is used across a large number of Bioconductor packages and is not specific to `CATALYST`. From a developer perspective it is not recommended to hard code names within functions (e.g. the requirement for `channel_name` and `marker_name` to be present) and allow flexibility in terms of user input. The column names of the panel are user defined, so if you want to use `CATALYST` for downstream analysis you will need to set them according to what `CATALYST` requires (as you did). Also have a look at [dittoSeq](https://www.bioconductor.org/packages//release/bioc/vignettes/dittoSeq/inst/doc/dittoSeq.html#71_dittoDimPlot__dittoScatterPlot) for visualisation of information contained in the `SingleCellContainer` without the need to adjust names. I hope that clarifies things and explains the design choice.

As for steinbock, I would say @jwindhager comments on this.

Cheers, Nils

**Comment by a-rayford** [comment]
Hi Nils,

Thanks for the feedback and suggestions for other packages beyond CATALYST. Also good to know that the steinbock panel.csv column names can be changed by the user, I wasn't aware of that.

For now v0.9.1 is working for me, just let me know if you need anything to reproduce the duplicate channel issue with .txt files in v0.12.0.

Cheers, 
Austin

**Comment by nilseling** [comment]
Hi Austin,
some of the column names are required by steinbock. But you could add `channel_name` and `marker_name` as extra columns. They will then also be read in by `imcRtools`. At the end it's probably easier to add them directly in R as you have done it now.

**Comment by koetjen** [comment]
I'm having the same same problem with generating panel.csv files containing multiple lines per channel. I used steinbock, version 0.12.0, `steinbock preprocess imc panel ` on a data folder containing 5 mcd files, no text files.  example from panel.csv:

Nd143 | 143Nd-vimentin 1 | 1 | 104
Nd143 | 143Nd-vimentin 2 | 1 | 104
Nd143 | 143Nd-vimentin 3 | 1 | 104
Nd143 | 143Nd-vimentin 4 | 1 | 104
Nd143 | 143Nd-vimentin 5 | 1 | 104

**Comment by jwindhager** [comment]
Apologies for this issue and thanks for reporting, @a-rayford and @koetjen! This should be fixed with v0.13.0.

Regarding the steinbock panel, please have a look at https://bodenmillergroup.github.io/steinbock/latest/file-types/#panel:

> The steinbock panel allows for further arbitrary columns.
